"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DEFAULT_ALLOW_TOUCH_THROUGH_OVERLAY = exports.DEFAULT_DISMISS_ON_SCROLL_DOWN = exports.DEFAULT_DISMISS_ON_OVERLAY_PRESS = exports.DEFAULT_OVERLAY_OPACITY = void 0;
const DEFAULT_OVERLAY_OPACITY = 0.5;
exports.DEFAULT_OVERLAY_OPACITY = DEFAULT_OVERLAY_OPACITY;
const DEFAULT_DISMISS_ON_OVERLAY_PRESS = true;
exports.DEFAULT_DISMISS_ON_OVERLAY_PRESS = DEFAULT_DISMISS_ON_OVERLAY_PRESS;
const DEFAULT_DISMISS_ON_SCROLL_DOWN = true;
exports.DEFAULT_DISMISS_ON_SCROLL_DOWN = DEFAULT_DISMISS_ON_SCROLL_DOWN;
const DEFAULT_ALLOW_TOUCH_THROUGH_OVERLAY = false;
exports.DEFAULT_ALLOW_TOUCH_THROUGH_OVERLAY = DEFAULT_ALLOW_TOUCH_THROUGH_OVERLAY;
//# sourceMappingURL=constants.js.map